# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    auto_inline: false
    configs:
        main_config:
                language: fr
                toolbar: [ ["Link", "Bold", "Italic", "BulletedList", "NumberedList", "center", "Underline", "TextColor" ], ['JustifyLeft', 'JustifyCenter', 'JustifyRight',]]
