vich_uploader:
    db_driver: orm
    mappings:
        lieux:
            uri_prefix: /place
            upload_destination: '%kernel.project_dir%/public/place'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
